### ISSUE TITLE
Swift-side process to discover new/changed items in ERA

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/pushmi_pullyu#1]
_From @pbinkley on December 7, 2016 20:43_

- capability to create JMS connection to HydraNorth
- capability on the Fedora side to receive this connection and hook it up to the local JMS service
- define JMS message: "this object id needs a preservation action"
- make Fedora generate these messages on changed objects - we don't know how to do this yet

Done: 
- Docker images for Pushmi-Pullyu and HydraNorth
- Pushmi-Pullyu receives JMS messages from HydraNorth containing the NOID of a changed object
- out of scope: aggregation of messages or communication with Swift

_Copied from original issue: ualbertalib/HydraNorth#1328_

**Comment by murny** [comment]
This issue is superseded by this issue #21. As we are no longer using JMS as this did not seem the best course of action. Closing out issue.
