### ISSUE TITLE
Set up development infrastructure for Swift (spike for investigation)

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/pushmi_pullyu#11]
_From @sfbetz on January 19, 2017 20:31_

-We need a vagrant or docker environment running swift avail to developers to push data from HydraNorth into
-Need to make sure special configuration matches production environment, eg. versioning
-training and review for devs
-maybe talk to Scholars Portal about their setup
-ansible playbook (if vagrant)
-ask Hydra community if anyone else is using Swift / OpenStack in production with Sufia

_Copied from original issue: ualbertalib/HydraNorth#1342_

**Comment by weiweishi** [comment]
The docker image is in git repository https://github.com/ualbertalib/DIDocker_Swift
