### ISSUE TITLE
Bag and tar the AIP

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/pushmi_pullyu#12]
We start with a local temporary directory containing the content fetched from Fedora, all validated against checksums as far as possible. 

We use a bagit app to create a bag (an officially-formatted bag according to the bagit spec), validate the bag, and then tar the local directory. 

There is a [bagit gem](https://github.com/tipr/bagit), which is in use in the digitization workflow.

Including a checksum of the bag.

**Comment by murny** [comment]
Closely related to Fedora/Solr data retrieval ticket #2. Chris has already started work on the Bagging and tarring of the AIP part as a result. Assigning to Chris.

His WIP PR for this is here #52

**Comment by murny** [comment]
Closed by PR #52.
