### ISSUE TITLE
Logging of preservation event

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/pushmi_pullyu#15]
Until we are on Fedora 4.7 with a full audit log, we will track preservation events in a log file (Log file is minimum viable product, database can come later if still needed especially if we want a dashboard):

Log file entry will contain the following information:
- NOID
- Timestamp of completion of preservation action
- Checksum(s) of AIP as ingested into Swift
- Metadata as specified in name-value pairs in Swift in the Lightweight AIP (list in document of AIP spec)

Other notable events should also be captured in logs (application logs). Such as any failures that occurred should be captured (timeouts, ID gone in fedora, etc, etc)

**Comment by murny** [comment]
From looking at latest PR #52, Looks like chris has started a bunch of work on this. Assigning and moving this ticket to In Progress.

**Comment by murny** [comment]
Might have been premature to assign chris and put this in progress. Removing this and putting back in queue.

He is doing the AIP logging not the logging preservation event. 

Should be easy however once the rest of work is completed (AIP creation #22 (#2 and #12) and AIP uploading to Swift #26 are complete). We can leverage some of his patterns for AIP logging for the separate preservation event logging (as both will be writing to a separate logging file).

**Comment by murny** [comment]
This has been completed in PR #72. Each successful swift upload will write the preservation event to both the application log and a seperate `preservation_events.log`. The logging event will look the following example:
```
I, [2017-06-05T12:21:08.700311 #16090]  INFO -- : 9p2909328 was successfully deposited into Swift Storage! 
Here are the details of this preservation event: 
	 NOID: '9p2909328' 
	 Timestamp of Completion: 'Fri, 02 Jun 2017 18:29:07 GMT' 
	 AIP Checksum: '0f32868de20f3b1d4685bfa497a2c243' 
	 Metadata: {"project-id"=>"9p2909328", "aip-version"=>"1.0", "promise"=>"bronze", "project"=>"ERA"} 
```
