### ISSUE TITLE
Update PMPY to retrieve file from ActiveStorage instead of Fedora

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/pushmi_pullyu#186]
This is trying to mediate issues with PMPY where PMPY tries to fetch file from Fedora and runs into "FileSet Not Found" issue - It's also to prepare us for the refactoring/removal of Fedora in our stack. 

Potential solution:
* identify the file in ActiveStorage possible through Solr? Rsync? allow a pull from PMPY to Gluster to fetch the file?
* Download the file through the web interface - but have potential security concerns.

**Comment by lagoan** [comment]
This has been addressed in PR #195
