### ISSUE TITLE
Pull Data from Fedora/Solr

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/pushmi_pullyu#2]
_From @pbinkley on December 7, 2016 20:43_

- run a fixity report in the Fedora API; save the output. Stop if the datastream is already corrupt in Fedora.
- retrieve Fedora information (see spec document https://docs.google.com/document/d/15qVr8naWHvUI1wgTLn-53zo4QO9QH3GMjXDCeLGq_sQ/edit#heading=h.sqqxwzm2947u)

Validate all available checksums - e.g. for the main datastream, after it is retrieved.

[Bash script mockup](https://gist.github.com/pbinkley/060ed60fb580c8c26324d07048ea1518) of process of fetching content from Fedora and populating a local directory ready to be bagged

See #22 for AIP creation

_Copied from original issue: ualbertalib/HydraNorth#1330_

**Comment by murny** [comment]
Closed by PR #52.
