### ISSUE TITLE
Server Setup (Production/Staging)

### ISSUE THREAD

**Issue by murny** [ualbertalib/pushmi_pullyu#20]
Infrastructure setup for production and staging environment for PushmiPullyu

- acquire server space for PushmiPullyu to live on for staging/production?
- Servers require access to redis/fedora/solr/swift (staging and production)
- Server probably needs ansible playbook for provisioning (needs ruby 2.3+. Not sure if any other requirements other then simple stuff like git etc?). 
- Unification of Redis instances in Production (or a 3rd Redis instance to act as a central queue).

**Comment by weiweishi** [comment]
This work is now completed. documentation is in https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/PMPY.md
