### ISSUE TITLE
ERROR -- : No such file or directory

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/pushmi_pullyu#235]
# error message while preserving an item

I, [2021-11-19T14:09:37.454151 #2228]  INFO -- : [theses - c00dae0f-a298-4bad-a8df-9085cd35ba6b]: tmp/work/c00dae0f-a298-4bad-a8df-9085cd35ba6b/data/objects/metadata/object_metadata.n3 -- Saved
I, [2021-11-19T14:09:37.454268 #2228]  INFO -- : [theses - c00dae0f-a298-4bad-a8df-9085cd35ba6b]: tmp/work/c00dae0f-a298-4bad-a8df-9085cd35ba6b/data/objects/metadata/files_metadata/file_order.xml -- Downloading from aip/v1/theses/c00dae0f-a298-4bad-a8df-9085cd35ba6b/filesets ...
I, [2021-11-19T14:09:37.495565 #2228]  INFO -- : [theses - c00dae0f-a298-4bad-a8df-9085cd35ba6b]: tmp/work/c00dae0f-a298-4bad-a8df-9085cd35ba6b/data/objects/metadata/files_metadata/file_order.xml -- Saved
D, [2021-11-19T14:09:37.529464 #2228] DEBUG -- : [theses - c00dae0f-a298-4bad-a8df-9085cd35ba6b]: Creating file set d7dfa7a4-8b6c-418d-af29-fee4dcbc4480 directories ...
D, [2021-11-19T14:09:37.530032 #2228] DEBUG -- : [theses - c00dae0f-a298-4bad-a8df-9085cd35ba6b]: Creating file set d7dfa7a4-8b6c-418d-af29-fee4dcbc4480 directories done
I, [2021-11-19T14:09:37.530160 #2228]  INFO -- : [theses - c00dae0f-a298-4bad-a8df-9085cd35ba6b]: tmp/work/c00dae0f-a298-4bad-a8df-9085cd35ba6b/data/objects/files/d7dfa7a4-8b6c-418d-af29-fee4dcbc4480/Hernandez_Medina_Stephany_202108_MSc.pdf -- Downloading from /era_assets/na/t7/nat75r9l7p5ncojj6i370gouo45n ...
E, [2021-11-19T14:09:37.530319 #2228] ERROR -- : No such file or directory @ rb_sysopen - /era_assets/na/t7/nat75r9l7p5ncojj6i370gouo45n (Errno::ENOENT)
/usr/lib64/ruby/2.6.0/fileutils.rb:1386:in `initialize'
/usr/lib64/ruby/2.6.0/fileutils.rb:1386:in `open'
/usr/lib64/ruby/2.6.0/fileutils.rb:1386:in `copy_file'
/usr/lib64/ruby/2.6.0/fileutils.rb:492:in `copy_file'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/aip/downloader.rb:66:in `copy_and_log'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/aip/downloader.rb:49:in `block in run'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/aip/downloader.rb:46:in `each'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/aip/downloader.rb:46:in `run'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/aip.rb:16:in `create'

# verification of the existence of "/era_assets/na/t7/nat75r9l7p5ncojj6i370gouo45n"

on era-app-stg-1.library.ualberta.ca:/era_assets/, the file **nat75r9l7p5ncojj6i370gouo45n** EXISTS as shown below

```
[root@era-app-stg-1 era_assets]# pwd
/era_assets
[root@era-app-stg-1 era_assets]# ls -lh na/t7
total 53M
-rw-r--r--. 1 apache apache 53M Nov 10 10:17 nat75r9l7p5ncojj6i370gouo45n

```

# conclusion

The error message "E, [2021-11-19T14:09:37.530319 #2228] ERROR -- : No such file or directory @ rb_sysopen - /era_assets/na/t7/nat75r9l7p5ncojj6i370gouo45n (Errno::ENOENT)"

- was caused in download.rb, 
- and its a code problem, not a data problem

We need to debug

**Comment by pgwillia** [comment]
I suspect that pushmi_pullyu is looking for a local path to era_assets.

**Comment by henryzhang87** [comment]
you are right! In the following function/method (aip/download.rb), the bold line is the culprit

  def copy_and_log(file_uuid, file_path)
   > remote = file_path[:file_path]
   > remote_checksum = file_path[:file_checksum]
   > files_path = file_set_dirs(file_uuid)[:files]
   > output_file = "#{files_path}/#{file_path[:file_name]}"
   > log_downloading(remote, output_file)
   >
   >  **FileUtils.copy_file(remote, output_file)**

**Comment by henryzhang87** [comment]
DI designed the PMPY to work with attached local /era_assets, which can be shared from Glusterfs 

In that situation, this is not an issue anymore
