### ISSUE TITLE
Adding communities and collection metadata to AIPs

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/pushmi_pullyu#255]
Currently AIPs are not being created for collections. There is important information about collections that we should be capturing in the preservation metadata in one way or another. This discussion can pick up again following on conversations about our preservation path going forward.

Reviewed details on what is currently being collected in the database for communities and collections (database schema: https://github.com/ualbertalib/jupiter/blob/b6961f5a3b9fd20fd552469d5872eca425f7d6bf/db/schema.rb#L91-L123

samples: https://gist.github.com/pgwillia/eed7dd858e17a9a67f9d90cb1d703adb#file-atmire_collection_data-csv and https://gist.github.com/pgwillia/eed7dd858e17a9a67f9d90cb1d703adb#file-atmire_community_data-csv). 

Properties for inclusion in AIPs for collections:

rdf:type (i.e., is a pcdm:Collection)
pcdm:memberOf (uuid for community)
dc:title
dc:description
dc:accessRights
ual:restrictedCollection
info:createdDate
ual:recordCreatedInJupiter

Properties for inclusion in AIPs for communities:

rdf:type (is a pcdm:Object, is a ual:Community)
dc:title
dc:description
dc:accessRights
info:createdDate
ual:recordCreatedInJupiter

_Originally posted by @sfarnel in https://github.com/ualbertalib/pushmi_pullyu/issues/196#issuecomment-1209738425_

**Comment by pgwillia** [comment]
We discussed a couple ways to do this
1. preserving collections and communities separately
2. adding collection and community metadata to the AIPs we preserve

We were leaning towards #2 but would have to enque all items in a community/collection any time it changed.

**Comment by lagoan** [comment]
I am trying to figure out the best place to store that metadata for the communities and collections.

Looking at the Item model I see and item can belong to multiple community/collection pairs. Going with [option 2](https://github.com/ualbertalib/pushmi_pullyu/issues/255#issuecomment-1209819285) would mean that the information for all community/collection pairs would reside in the AIP.

Would the best place for that metadata be in the ``object_metadata.n3`` file? Here is an [example](https://github.com/ualbertalib/jupiter/blob/master/test/fixtures/files/n3/items/e2ec88e3-3266-4e95-8575-8b04fac2a679-base.n3) of the current contents of that file.

The ``object_metadata.n3`` has the predicate [http://pcdm.org/models#memberOf](https://github.com/ualbertalib/jupiter/blob/46f1c99e64cd893735d1d612e472e53746b95643/test/fixtures/files/n3/items/e2ec88e3-3266-4e95-8575-8b04fac2a679-base.n3#L13) which contains the collections to which the entity belongs. Would we change and add a container for each community/collection parent pair? If so, what would it look like? 

Alternatively, we could place the community/collection information on a separate file inside the AIP. That file could contain just a list of community/collection pairs. Which predicates could be used to describe these pairs?

Lastly, we could just add a list of the information of both communities and collections to which the item belongs. Each collection could have its information, including the parent's community UUID.

What are your thoughts on this?

**Comment by lagoan** [comment]
Now pinging members of the metadata team (@sfarnel @anayram @lucfagnan).

**Comment by sfarnel** [comment]
Thank you @pgwillia @lagoan Yes, @anayram that is absolutely right; option #1 is what is required

**Comment by sfarnel** [comment]
Thanks very much @ConnorSheremeta this looks good to me. @anayram @lucfagnan do you have any concerns?

**Comment by anayram** [comment]
@ConnorSheremeta @sfarnel @lucfagnan all looks good to me (all properties are included). Thanks so much @ConnorSheremeta !
