### ISSUE TITLE
Simplify local setup

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/pushmi_pullyu#294]
In order to get this project running locally 

```
PushmiPullyu.options[:jupiter][:user] = 'ditech@ualberta.ca'
PushmiPullyu.options[:jupiter][:api_key] = '3eeb395e-63b7-11ea-bc55-0242ac130003'
```
Has to be added to the top of the run method in pushmipullyu/lib/pushmipullyu/cli.rb

There has to be a better way to not have this manual step.

**Comment by pgwillia** [comment]
Another option is to use envars. 
```
export JUPITER_API_KEY=3eeb395e-63b7-11ea-bc55-0242ac130003
export JUPITER_USER=ditech@ualberta.ca
```
Could be added to documentation.

**Comment by pgwillia** [comment]
Closed by https://github.com/ualbertalib/pushmi_pullyu/pull/304
