### ISSUE TITLE
Code deployment to environments

### ISSUE THREAD

**Issue by murny** [ualbertalib/pushmi_pullyu#31]
### Deployment of code to environments

How would this look like? Can this be done from CI? Capistrano? Or would this require Henry and RPM packaging. 

This pretty much depends on what the system admins will do and allow (SSH access? Environment variables?). Assuming you have a server that has been provisioned with ruby (among other things) from ticket #20. We need to deploy our code onto this server and maintain this accordingly. 

### Manual approach? 

You could ssh into the server, git clone latest code from this git repo or install latest gem (`gem update pushmi_pullyu`), then restart PushmiPullyu to pick up the newest code base.

### Automatic approach? 

Well you could pretty much do the exact thing above using something like Capistrano.  Capistrano is provides alot of nice goodies such as the ability to deploy your code from github, rollback code (which is something that we can't do in HN from previous incidents), doing a dry run of your deployment, run any tasks on your server for maintenance, restarting, clearing caches, etc. Best part is it is repeatable and done in code instead of having someone manually doing this.

Once you have capistrano configured, then it would be just `cap <environment> deploy`. This could also be utilised to automate this deployment for some of our environments (deployment to staging or sandbox environment) from a successful continuous integration (TravisCI) build too . TravisCI allows setting environment variables either through the repo settings or encrypted in the `.travis.yml`. Read more here:
https://docs.travis-ci.com/user/environment-variables/
https://docs.travis-ci.com/user/deployment/

NOTE: The exact same thing that capistrano does, can be done via Ansible as well.

### Configurating PushmiPullyu?

For regarding configuration of pushmi_pullyu there is a few options. We can use a config file (with env vars) to do most of this configuration. Another option is by passing these options in when running the CLI. See project Readme

### RPM deployment

TODO: fill this in.

If this is what we will do, we need this documented. We currently use RPM deployments for HN. No idea what this looks like.

### Docker deployment?

TODO: Basically you would use jeff's dockerfile to package up the code and build a docker image. Then push it up to dockerhub. On the server, you would then pull down this image and run it. Probably could wrap this in a simple docker-compose.yml to make this straightforward and familiar (should be the approach for other rails apps we have). You can also pass in the environment variables/env_file for any configuration needed. To update to latest image if already running, you can just stop existing container, build new container from new image, then rerun, etc. For example:
 ```bash
docker-compose down
docker-compose pull
# if rails app you would run migrations: docker-compose run rails rake db:migrate
docker-compose up -d
```
If going this route, instead of provisioning the server with ruby, you would provision it with docker/docker-compose/git (to grab docker-compose.yml file).

### For Rollbar we need to:

- [x] Create a Prod Rollbar owner account under the dittest delegated account
- [ ] Set up rate limits (Free tier is 5000 errors per month, and if dittest owns the same account as Hydranorth uses that's across all projects, so I'd suggest we want a strict limit of (5000/2)/31 == ~80 errors per day (which is still 80 more errors than we are currently notified of at the moment...).
- [ ] Devs create accounts and get invited to project
- [ ] Ansible deploy script is updated to add Rollbar token to production config/secrets.yml
- [ ] ???
- [ ] Profit

**Comment by murny** [comment]
Updated ticket with a bunch of documentation of how we might want to tackle this. Putting this back in backlog

**Comment by weiweishi** [comment]
@murny could you please update this ticket with what's been done, what's blocking the deployment and the next steps in the ticket? thanks.

**Comment by murny** [comment]
What's been done?

**Comment by murny** [comment]
# What's been done?

**Comment by murny** [comment]
### Whats been done?

- Logged into Pushmi Pullyu test VM, install ruby via yum
- Gem installed pushmi_pullyu
- Confirmed I could access Solr, but couldnt access Fedora/Redis/Swift (which is apparently resolved now) which was blocking this from going further

### What needs to be done?
- Confirm again if I can access Fedora/Redis/Swift from VM (assuming passwords are given or havent changed)
- If so, add config file for pushmi pullyu (with all settings that PMPY requires including the various end points for Solr/Swift/Redis/Fedora)
- Run pushmi pullyu with config file ( `pushmi_pullyu start -C some/config.yml`)....hopefully all works?
- Give good test run via era-test and check if file is uploaded into swift (and verify logs)?

**Comment by weiweishi** [comment]
Deployment documentation is available at: https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/PMPY.md
