### ISSUE TITLE
Add application monitoring for PushmiPullyu

### ISSUE THREAD

**Issue by murny** [ualbertalib/pushmi_pullyu#32]
Bring in something like ~~newrelic/skylight~~ (can't use for pushmipullyu since there is no webstack?) errbit  (self hosted error tracker based on airbrake), or honeybadger (which apparently is free for non-commerical open source projects?)/etc for PushmiPullyu so we can get some eyes on how PushmiPullyu is performing when in production and being alerted on failures/issues.

**Comment by pbinkley** [comment]
Since this might become a model for monitoring of rails apps in our environment (at least, I hope we wouldn't end up doing this in different ways for different projects), we should include @redlibrarian in the discussion.
