### ISSUE TITLE
Investigate using pushmi_pullyu with OLRC

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/pushmi_pullyu#349]
Investigate using pushmi_pullyu with OLRC

I think we will likely need to re-configure PMPY to point to OLRC this fall.  With that we might take several approaches - simple configuration of existing PMPY against a new swift container using the current API approach, or a more complex project of integrating Duracloud into our PMPY pipeline. - Kenton

First steps
1. Meet with Kenton for context and make this a ticket.
2. Ask for credentials that we'll need and the container we'll write to for this test.

Maybe the first step is seeing if our development environment will write to OLRC.

**Comment by jefferya** [comment]
Here are the major differences I've experienced when converting the CWRC perseveration tooling to use OLRC Swift as a drop-in replacement for UAL Swift.

The main difference, OLRC requires an additional property, a domain as part of the authentication. As of 2023-08-15, I'm testing to see if further changes are required: <https://github.com/ualbertalib/cwrc_preservation/tree/jefferya/olrc_compatibility>

* OLRC OpenStack RC file env var `OS_USER_DOMAIN_NAME` to OpenStack Gem connection property `user_domain`
* OLRC OpenStack RC file env var `OS_PROJECT_DOMAIN_ID` to OpenStack Gem connection property `project_domain_id`
 
The ruby-openstack connection is defined here: <https://github.com/ruby-openstack/ruby-openstack/blob/master/lib/openstack/connection.rb> 

The aforementioned OpenStack RC file can be downloaded from the Horizon UI via the upper right-hand corner user account menu.

**Comment by lagoan** [comment]
Thanks to @jefferya work the process of redirecting PMPY to OLRC has been straightforward. 

The following shell command works for me to test authentication:

```bash
swift --os-auth-url 'AUTH_URL' \
      --os-username 'USER_NAME' \
      --os-user-domain-name 'USER_DOMAIN_NAME' \
      --os-password  'PASSWORD' \
      --os-project-name 'PROJECT_NAME' \
      --os-project-domain-name 'PROJECT_DOMAIN_NAME' \
      --auth-version 3 \
      stat
```

The changes in the codebase to redirect pushing the items to OLRC Swift have been mirroring the configuration changes used to authenticate. 

I've successfully pushed synthetic data to a new container in OLRC.

My next steps include:

- [ ] Testing pushing real data from a database dump in my development environment
- [ ] Test with real data, including files, from our staging environment
- [ ] Configuring the docker image of OpenStack Swift to use v3 for authentication
- [ ] Once our OpenStack Swift instance is configured, I will be able to create the tests for development
