### ISSUE TITLE
Update PushMiPullYu Redis connection to use url

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/pushmi_pullyu#89]
This is related to https://github.com/ualbertalib/pushmi_pullyu/issues/87

Current configuration of PMPY uses host/port for redis connection. https://github.com/ualbertalib/pushmi_pullyu/blob/master/lib/pushmi_pullyu/cli.rb#L205-L211

This should be updated to use redis_url as _redis:// URL_:

```redis://:p4ssw0rd@10.0.1.1:6380/15```

So that it can use a password for authentication, and potentially different database as needed.

**Comment by murny** [comment]
I'll be working on this one today. Should have a PR out before the end of the day.
